# Build Stage
FROM node:20 as build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps
COPY . .

# Solo necesitamos la URL del API
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN NODE_OPTIONS="--max-old-space-size=512" npm run build

# Production Stage - Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
