-- ============================================================
-- REFORMULACIÓN PEDAGÓGICA — DESAFÍOS FASE 4 Y FASE 5 (12 CONTEXTOS)
-- ============================================================

BEGIN;

-- 1. Crear tabla de backup si no existe
CREATE TABLE IF NOT EXISTS _backup_desafios_f4_f5 AS 
SELECT * FROM preguntas 
WHERE (fase_id = 4 OR fase_id = 5) 
  AND seccion IN (1011, 1012, 1013, 2011, 2012, 2013, 3011, 3012, 3013, 4011, 4012, 4013);

-- ============================================================
-- FASE 4 - MÓDULO 1 (1011, 1012, 1013) — Fracción Visual
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN 'Una barra de chocolate está dividida en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' partes iguales y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas son de chocolate amargo. ¿Qué fracción representa el chocolate amargo?'
  WHEN 1 THEN 'Una pizza redonda se cortó en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' rebanadas iguales y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas tienen champiñones. ¿Qué fracción representa las rebanadas con champiñones?'
  WHEN 2 THEN 'Una tarta de cumpleaños se dividió en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' porciones iguales y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas son de fresa. ¿Qué fracción representa las porciones de fresa?'
  WHEN 3 THEN 'Un huerto escolar rectangular está dividido en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' parcelas iguales y en ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas se plantaron zanahorias. ¿Qué fracción representa las parcelas de zanahoria?'
  WHEN 4 THEN 'Una ventana de vidrio tiene ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' paneles del mismo tamaño y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellos están pintados de azul. ¿Qué fracción representa los paneles azules?'
  WHEN 5 THEN 'Un queso artesanal está cortado en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' cuñas iguales y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas se sirvieron en un plato. ¿Qué fracción representa las cuñas servidas?'
  WHEN 6 THEN 'Un mural escolar rectangular está dividido en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' franjas verticales del mismo tamaño y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas están pintadas de amarillo. ¿Qué fracción representa las franjas amarillas?'
  WHEN 7 THEN 'Un jardín rectangular está dividido en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' secciones cuadradas del mismo tamaño y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas tienen rosas rojas. ¿Qué fracción representa las secciones con rosas rojas?'
  WHEN 8 THEN 'Un pan rectangular se rebanó en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' trozos iguales y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellos tienen mantequilla. ¿Qué fracción representa los trozos con mantequilla?'
  WHEN 9 THEN 'Un molde de gelatina se cortó en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' cubos del mismo tamaño y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellos son de sabor limón. ¿Qué fracción representa los cubos de limón?'
  WHEN 10 THEN 'Una alfombra rectangular está dividida en ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' franjas horizontales iguales y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellas son de color verde. ¿Qué fracción representa las franjas verdes?'
  WHEN 11 THEN 'Un mosaico cuadrado está compuesto por ' || COALESCE(substring(b.enunciado FROM 'dividido en (\d+) tiras'), 'ERROR_CAPTURA') || ' mosaicos pequeños del mismo tamaño y ' || COALESCE(substring(b.enunciado FROM '(\d+) de ellas son'), 'ERROR_CAPTURA') || ' de ellos son de color blanco. ¿Qué fracción representa los mosaicos blancos?'
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 4 AND p.seccion IN (1011, 1012, 1013);

-- ============================================================
-- FASE 4 - MÓDULO 2 (2011, 2012, 2013) — Fracción de Cantidad
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN 'En una caja de ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' lápices de colores, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' utilizó exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' para dibujar. ¿Cuántos lápices utilizó?'
  WHEN 1 THEN 'En una biblioteca con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' libros infantiles, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' leyó exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' de ellos este mes. ¿Cuántos libros leyó?'
  WHEN 2 THEN 'En una canasta con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' manzanas rojas, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' regaló exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' a sus amigos de clase. ¿Cuántas manzanas regaló?'
  WHEN 3 THEN 'En una bolsa con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' caramelos de fresa, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' se comió exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' durante la semana. ¿Cuántos caramelos se comió?'
  WHEN 4 THEN 'En una fiesta con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' globos inflados, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' decoró el salón principal usando exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' del total. ¿Cuántos globos usó?'
  WHEN 5 THEN 'En un set de ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' bloques de construcción, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' armó una torre usando exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' de ellos. ¿Cuántos bloques utilizó?'
  WHEN 6 THEN 'En un álbum de ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' estampitas de fútbol, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' pegó exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' en la primera página. ¿Cuántas estampitas pegó?'
  WHEN 7 THEN 'En una bandeja con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' galletas de chocolate, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' sirvió exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' en un plato para compartir. ¿Cuántas galletas sirvió?'
  WHEN 8 THEN 'En un jardín con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' hermosas flores sembradas, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' cortó exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' para armar un ramo. ¿Cuántas flores cortó?'
  WHEN 9 THEN 'En una alcancía con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' monedas de un peso, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' gastó exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' en comprar un juguete. ¿Cuántas monedas gastó?'
  WHEN 10 THEN 'En un estuche con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' crayones nuevos, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' prestó exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' a su compañero de mesa. ¿Cuántos crayones prestó?'
  WHEN 11 THEN 'En un paquete con ' || COALESCE(substring(b.enunciado FROM 'con (\d+)'), 'ERROR_CAPTURA') || ' hojas de papel de colores, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) usó'), 'ERROR_CAPTURA') || ' dobló exactamente ' || COALESCE(substring(b.enunciado FROM 'exactamente (\d+/\d+)'), 'ERROR_CAPTURA') || ' para hacer aviones de papel. ¿Cuántas hojas dobló?'
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 4 AND p.seccion IN (2011, 2012, 2013);

-- ============================================================
-- FASE 4 - MÓDULO 3 (3011, 3012, 3013) — Porcentajes Rápidos y Promedios
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE 
  -- CASO A: PROMEDIOS
  WHEN b.enunciado LIKE '%exámenes%' THEN
    CASE (p.id % 12)
      WHEN 0 THEN 'En tres partidos de baloncesto, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' anotó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' puntos. ¿Cuál es el promedio de puntos anotados por partido?'
      WHEN 1 THEN COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' leyó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' minutos durante tres días seguidos. ¿Cuál es el promedio de minutos leídos por día?'
      WHEN 2 THEN 'En tres semanas, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' ahorró ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' monedas en su alcancía. ¿Cuál es el promedio de monedas ahorradas por semana?'
      WHEN 3 THEN COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' leyó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' páginas de su cuento favorito en tres tardes. ¿Cuál es el promedio de páginas leídas por tarde?'
      WHEN 4 THEN 'En tres divertidos juegos de canicas, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' ganó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' canicas. ¿Cuál es el promedio de canicas ganadas por juego?'
      WHEN 5 THEN 'En tres caminatas con su mascota, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' recorrió ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' kilómetros. ¿Cuál es el promedio de kilómetros por caminata?'
      WHEN 6 THEN COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' horneó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' galletas en tres bandejas distintas. ¿Cuál es el promedio de galletas por bandeja?'
      WHEN 7 THEN 'En tres salones de clase, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' recolectó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' lápices perdidos. ¿Cuál es el promedio de lápices recolectados por salón?'
      WHEN 8 THEN COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' tomó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' hermosas fotos durante tres paseos al parque. ¿Cuál es el promedio de fotos tomadas por paseo?'
      WHEN 9 THEN 'En tres exámenes de práctica, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' respondió correctamente ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' preguntas. ¿Cuál es el promedio de aciertos por examen?'
      WHEN 10 THEN COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' recolectó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' naranjas de tres árboles de su jardín. ¿Cuál es el promedio de naranjas por árbol?'
      WHEN 11 THEN 'Durante tres días, ' || COALESCE(substring(b.enunciado FROM 'exámenes de ([A-Z][a-záéíóúüñ]+) son'), 'ERROR_CAPTURA') || ' ordenó ' || COALESCE(substring(b.enunciado FROM 'son (\d+),'), 'ERROR_CAPTURA') || ', ' || COALESCE(substring(b.enunciado FROM ', (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+)\.'), 'ERROR_CAPTURA') || ' juguetes en su caja. ¿Cuál es el promedio de juguetes ordenados por día?'
    END
  -- CASO B: PORCENTAJES
  ELSE
    CASE (p.id % 12)
      WHEN 0 THEN 'Un informe escolar indica que el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% de los ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' libros de la biblioteca son cuentos ilustrados. ¿Cuántos libros son cuentos ilustrados?'
      WHEN 1 THEN 'En un colegio de ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' estudiantes, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% asistió hoy al taller de ajedrez. ¿Cuántos estudiantes asistieron al taller?'
      WHEN 2 THEN 'En un huerto con ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' árboles frutales, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% son limoneros maduros. ¿Cuántos árboles son limoneros maduros?'
      WHEN 3 THEN 'En una juguetería con ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' juguetes en oferta, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% son bloques de madera. ¿Cuántos juguetes de madera hay en oferta?'
      WHEN 4 THEN 'De un grupo de ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' alumnos que rindieron el examen, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% obtuvo la calificación máxima. ¿Cuántos alumnos obtuvieron la máxima calificación?'
      WHEN 5 THEN 'Un libro de cuentos tiene ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' páginas en total y el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% de ellas tiene ilustraciones de colores. ¿Cuántas páginas tienen ilustraciones?'
      WHEN 6 THEN 'En una caja con ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' de manzanas recién recolectadas, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% son manzanas rojas y dulces. ¿Cuántas manzanas son dulces?'
      WHEN 7 THEN 'Para una obra de teatro infantil con ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' asientos disponibles, se vendió el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% de las entradas. ¿Cuántas entradas se vendieron?'
      WHEN 8 THEN 'En un festival de globos con ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' globos en el aire, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% son de color azul brillante. ¿Cuántos globos son azules?'
      WHEN 9 THEN 'En una prueba de matemáticas de ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' preguntas, Lucas respondió correctamente el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% del total. ¿Cuántas preguntas respondió bien?'
      WHEN 10 THEN 'En un estacionamiento con ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' vehículos, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% son coches eléctricos modernos. ¿Cuántos vehículos eléctricos hay en el estacionamiento?'
      WHEN 11 THEN 'De las ' || COALESCE(substring(b.enunciado FROM 'de los (\d+) encuestados'), 'ERROR_CAPTURA') || ' semillas de girasol plantadas en la huerta escolar, el ' || COALESCE(substring(b.enunciado FROM 'el (\d+)%'), 'ERROR_CAPTURA') || '% logró germinar con éxito. ¿Cuántas semillas germinaron?'
    END
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 4 AND p.seccion IN (3011, 3012, 3013);

-- ============================================================
-- FASE 4 - MÓDULO 4 (4011, 4012, 4013) — Razón y Mezclas
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN 'Para preparar limonada, se usan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' partes de agua por cada 1 parte de jugo de limón. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' prepara una jarra usando ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' partes de jugo de limón, ¿cuántas partes de agua necesita para mantener la razón?'
  WHEN 1 THEN 'Para hacer pintura verde, se mezclan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' partes de pintura amarilla por cada 1 parte de azul. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' usa ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' partes de azul, ¿cuántas partes de amarilla necesita?'
  WHEN 2 THEN 'Para armar un estante, se requieren ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' tornillos por cada 1 tabla de madera. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' construye una estructura usando ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' tablas, ¿cuántos tornillos necesita en total?'
  WHEN 3 THEN 'Una receta requiere ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' tazas de leche por cada 1 taza de arroz. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' cocina usando ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' tazas de arroz, ¿cuántas tazas de leche debe agregar?'
  WHEN 4 THEN 'Para hacer chocolate caliente, se usan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' cucharadas de leche en polvo por cada 1 cucharada de cacao. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' mezcla ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' cucharadas de cacao, ¿cuántas de leche necesita?'
  WHEN 5 THEN 'Para unas galletas, se usan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' tazas de harina por cada 1 taza de azúcar. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' usa ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' tazas de azúcar, ¿cuántas tazas de harina requiere para la masa?'
  WHEN 6 THEN 'Para preparar la comida, se mezclan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' porciones de croquetas secas por cada 1 porción de agua tibia. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' sirve ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' porciones de agua, ¿cuántas croquetas debe agregar?'
  WHEN 7 THEN 'Un desinfectante casero lleva ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' partes de agua por cada 1 parte de jabón concentrado. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' usa ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' partes de jabón, ¿cuántas partes de agua requiere la mezcla?'
  WHEN 8 THEN 'Para hacer plastilina casera, se mezclan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' partes de harina por cada 1 parte de sal fina. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' usa ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' partes de sal, ¿cuántas de harina necesita para la mezcla?'
  WHEN 9 THEN 'Una infusión requiere ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' tazas de agua por cada 1 cucharada de hojas de té. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' prepara una tetera con ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' cucharadas de hojas, ¿cuántas tazas de agua debe servir?'
  WHEN 10 THEN 'Un jugo mixto lleva ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' partes de jugo de naranja por cada 1 parte de zanahoria. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' exprime ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' partes de zanahoria, ¿cuántas de naranja requiere?'
  WHEN 11 THEN 'Para diluir pegamento, se mezclan ' || COALESCE(substring(b.enunciado FROM '(\d+) partes? de solvente'), 'ERROR_CAPTURA') || ' partes de cola blanca por cada 1 parte de agua. Si ' || COALESCE(substring(b.enunciado FROM 'Si ([A-Z][a-záéíóúüñ]+) elabora'), 'ERROR_CAPTURA') || ' vierte ' || COALESCE(substring(b.enunciado FROM 'usando (\d+) partes? de fragancia'), 'ERROR_CAPTURA') || ' partes de agua, ¿cuántas partes de cola blanca necesita?'

END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 4 AND p.seccion IN (4011, 4012, 4013);


-- ============================================================
-- FASE 5 - MÓDULO 1 (1011, 1012, 1013) — Perímetro de Rectángulos
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere colocar una cerca de madera alrededor de su jardín rectangular. Si los lados miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros, ¿cuántos metros de cerca necesita en total?'
  WHEN 1 THEN 'En la escuela, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere delimitar un huerto rectangular con cinta de colores. Si las dimensiones son ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros, ¿cuál es la longitud total de la cinta necesaria?'
  WHEN 2 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere ponerle un marco de madera a su pintura rectangular favorita. Si los lados del cuadro miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' centímetros, ¿cuántos centímetros de madera usará para el marco?'
  WHEN 3 THEN 'Para mayor seguridad, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere cercar un área rectangular de juegos en su patio. Si los lados miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros, ¿cuánto mide el perímetro del área de juegos?'
  WHEN 4 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere colocar una baranda de seguridad alrededor de su piscina rectangular. Si los lados miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros, ¿cuántos metros de baranda instalará en total?'
  WHEN 5 THEN 'En el club deportivo, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere pintar la línea exterior de una cancha rectangular. Si los lados miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros, ¿cuántos metros de línea pintará en total?'
  WHEN 6 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' quiere colocar un zócalo de madera alrededor de su habitación rectangular. Si las paredes miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros de largo, ¿cuántos metros de zócalo necesita?'
  WHEN 7 THEN 'Para proteger los bordes de su mesa rectangular de tareas, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' pegará una cinta protectora. Si los lados miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' centímetros, ¿cuánta cinta usará?'
  WHEN 8 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' colocará luces LED alrededor del marco de su gran espejo rectangular. Si las medidas son ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' centímetros, ¿qué longitud de tira LED necesita en total?'
  WHEN 9 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' corre por el sendero que bordea un parque rectangular todas las mañanas. Si los lados miden ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' metros, ¿qué distancia recorre en una vuelta completa?'
  WHEN 10 THEN 'Para Navidad, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' decorará el contorno de una ventana rectangular con guirnaldas brillantes. Si el marco mide ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' centímetros, ¿cuántos centímetros de guirnalda necesita?'
  WHEN 11 THEN 'El maestro le pide a ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) quiere'), 'ERROR_CAPTURA') || ' colocar un borde metálico decorativo a la pizarra rectangular del salón. Si mide ' || COALESCE(substring(b.enunciado FROM 'miden (\d+) y'), 'ERROR_CAPTURA') || ' y ' || COALESCE(substring(b.enunciado FROM 'y (\d+) unidades'), 'ERROR_CAPTURA') || ' centímetros por lado, ¿cuánto material se usará?'
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 5 AND p.seccion IN (1011, 1012, 1013);

-- ============================================================
-- FASE 5 - MÓDULO 2 (2011, 2012, 2013) — Área de Rectángulos
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' desea cubrir el piso rectangular de su habitación con alfombra de colores. Si la base mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros y la altura ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' metros, ¿cuántos metros cuadrados de alfombra necesita?'
  WHEN 1 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' quiere colocar césped artificial en un sector rectangular de su jardín. Si mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base y ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' metros de altura, ¿cuál es el área total a cubrir?'
  WHEN 2 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' diseñará un mosaico rectangular en la pared de su cocina usando azulejos. Si el espacio tiene ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' centímetros de base y ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿qué superficie cubrirá?'
  WHEN 3 THEN 'Para sembrar fresas maduras, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' preparó un terreno rectangular de ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base por ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' metros de altura. ¿De cuántos metros cuadrados dispone para sembrar?'
  WHEN 4 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' quiere pintar una pared rectangular de su sala de color azul. Si la base mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros y la altura ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' metros, ¿cuánta superficie de pared pintará?'
  WHEN 5 THEN 'Para un lindo proyecto de arte, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' quiere barnizar la superficie rectangular de su mesa de madera. Si mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' centímetros de base por ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿cuál es el área que barnizará?'
  WHEN 6 THEN 'Los alumnos ayudaron a ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' a forrar la cartelera rectangular del colegio con papel afiche. Si tiene ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base por ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿qué área de papel usaron?'
  WHEN 7 THEN 'En el nuevo salón de fiestas, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' instalará una pista de baile rectangular de madera. Si la pista mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base y ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿cuál es su área total?'
  WHEN 8 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' mandó a hacer una cortina para cubrir por completo una ventana rectangular. Si la ventana tiene ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base por ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿cuántos metros cuadrados de tela se requieren?'
  WHEN 9 THEN 'En la nueva escuela de deportes, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' quiere pulir el suelo de madera de la cancha rectangular. Si mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base y ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿qué superficie se pulirá?'
  WHEN 10 THEN 'En el parque municipal del barrio, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' diseñó un estanque rectangular para peces. Si el estanque tiene ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' metros de base por ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿cuál es el área de la superficie del agua?'
  WHEN 11 THEN 'Para proteger su cuaderno de dibujo rectangular, ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) necesita'), 'ERROR_CAPTURA') || ' lo cubrirá con papel transparente. Si el cuaderno mide ' || COALESCE(substring(b.enunciado FROM 'La base mide (\d+)'), 'ERROR_CAPTURA') || ' centímetros de base y ' || COALESCE(substring(b.enunciado FROM 'la altura (\d+)'), 'ERROR_CAPTURA') || ' de altura, ¿qué área de papel utilizará?'
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 5 AND p.seccion IN (2011, 2012, 2013);

-- ============================================================
-- FASE 5 - MÓDULO 3 (3011, 3012, 3013) — Área Sombreada
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' hizo un marco de fotos rectangular. El área total del portarretratos es de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm² y el espacio central para la foto es de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm². ¿Cuál es el área del marco de madera?'
  WHEN 1 THEN 'En su terreno rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' m², ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' construyó una piscina de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' m² y dejó el resto para césped. ¿Cuántos metros cuadrados de césped tiene el jardín?'
  WHEN 2 THEN 'Una ventana rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm² tiene un panel de madera decorativo en el centro que mide ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm². ¿Cuál es el área restante de vidrio de la ventana de ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || '?'
  WHEN 3 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' recortó una tarjeta rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm² y pegó una foto rectangular de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm² en el medio. ¿Qué área de cartulina queda visible alrededor de la foto?'
  WHEN 4 THEN 'Un patio rectangular tiene un área total de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' m². ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' diseñó un cantero de flores en el centro de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' m². ¿Cuál es el área libre de baldosas en el patio?'
  WHEN 5 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' colocó un camino de mesa rectangular de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm² sobre un mantel rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm². ¿Qué área del mantel original queda al descubierto?'
  WHEN 6 THEN 'En una pared rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' m², ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' colgó un gran cuadro rectangular que cubre exactamente ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' m². ¿Qué superficie de pared queda libre de cuadros?'
  WHEN 7 THEN COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' hizo un panel de mosaicos de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm² con un espejo rectangular de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm² en el centro. ¿Cuál es el área cubierta únicamente por mosaicos?'
  WHEN 8 THEN 'En un terreno rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' m², ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' delimitó una zona de arena de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' m² para jugar voleibol y dejó el resto como césped. ¿Qué superficie tiene césped?'
  WHEN 9 THEN 'Una placa metálica rectangular tiene un área de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm² y ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' grabó un rectángulo central de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm² con su nombre. ¿Cuál es el área de metal liso alrededor del grabado?'
  WHEN 10 THEN 'Una caja de regalo de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' cm² tiene una ventana de acetato rectangular en la tapa de ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' cm² para ver el interior. ¿Cuál es el área de cartón de la tapa hecha por ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || '?'
  WHEN 11 THEN 'Una alfombra rectangular de ' || COALESCE(substring(b.enunciado FROM 'exterior de (\d+)'), 'ERROR_CAPTURA') || ' m² diseñada por ' || COALESCE(substring(b.enunciado FROM '([A-Z][a-záéíóúüñ]+) construyó'), 'ERROR_CAPTURA') || ' tiene un patrón de flores en el centro que cubre ' || COALESCE(substring(b.enunciado FROM 'interior de (\d+)'), 'ERROR_CAPTURA') || ' m² y el resto es liso. ¿Qué área de la alfombra es de color liso?'
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 5 AND p.seccion IN (3011, 3012, 3013);

-- ============================================================
-- FASE 5 - MÓDULO 4 (4011, 4012, 4013) — Pitágoras / Diagonales
-- ============================================================
UPDATE preguntas p
SET enunciado = CASE (p.id % 12)
  WHEN 0 THEN 'Cuando ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' va a comprar un televisor, ¿qué línea de medida física se utiliza universalmente para anunciar su tamaño en pulgadas?'
  WHEN 1 THEN 'Al elegir un nuevo monitor para su computadora, ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' lee el tamaño expresado en pulgadas. ¿A qué línea o medida física del monitor corresponde este valor?'
  WHEN 2 THEN COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' nota que las pantallas de los teléfonos celulares se miden en pulgadas. ¿Qué medida del rectángulo de la pantalla representa este valor comercial?'
  WHEN 3 THEN COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' investiga sobre las especificaciones de una tableta nueva y ve que mide 10 pulgadas. ¿Qué línea física de la pantalla mide 10 pulgadas?'
  WHEN 4 THEN 'Al medir la pantalla de su laptop, ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' se da cuenta de que la medida en pulgadas corresponde a la línea que cruza de una esquina a otra. ¿Cómo se llama esta línea?'
  WHEN 5 THEN COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' tiene una consola portátil de videojuegos. Si el tamaño de la pantalla está dado en pulgadas, ¿qué línea de la pantalla rectangular representa esta medida?'
  WHEN 6 THEN 'Para su cumpleaños, ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' quiere un reloj inteligente de pantalla rectangular. El fabricante indica el tamaño de la pantalla en pulgadas midiendo cuál de sus líneas físicas?'
  WHEN 7 THEN 'En un folleto del cine de la ciudad, ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' ve que la pantalla gigante se clasifica por pulgadas. ¿Qué línea que conecta esquinas opuestas determina este tamaño?'
  WHEN 8 THEN COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' tiene un marco de fotos digital rectangular. El manual dice que mide 8 pulgadas. ¿Qué medida física de la pantalla del marco representa esta cifra?'
  WHEN 9 THEN 'En el auto de su papá, ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' observa la pantalla del GPS. El tamaño en pulgadas de este dispositivo se mide siguiendo cuál de sus líneas rectangulares?'
  WHEN 10 THEN COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' lee cuentos en un libro electrónico. La descripción del dispositivo indica 6 pulgadas de tamaño de pantalla. ¿Qué dimensión rectangular del dispositivo mide 6 pulgadas?'
  WHEN 11 THEN 'En la tienda de electrodomésticos, ' || COALESCE(substring(b.enunciado FROM 'Cuando ([A-Z][a-záéíóúüñ]+) va'), 'ERROR_CAPTURA') || ' ve un refrigerador inteligente con una pantalla integrada. El tamaño de esa pantalla en pulgadas está definido por cuál de sus líneas físicas?'
END
FROM _backup_desafios_f4_f5 b
WHERE p.id = b.id AND p.fase_id = 5 AND p.seccion IN (4011, 4012, 4013);


-- ============================================================
-- VALIDACIONES POST-MIGRACIÓN
-- ============================================================

-- ============================================================
-- CONSULTAS DE DIAGNÓSTICO
-- ============================================================
SELECT id, fase_id, seccion, enunciado 
FROM preguntas 
WHERE (fase_id = 4 OR fase_id = 5) 
  AND seccion IN (1011, 1012, 1013, 2011, 2012, 2013, 3011, 3012, 3013, 4011, 4012, 4013)
  AND enunciado LIKE '%ERROR_CAPTURA%'
ORDER BY id;

-- Mostrar también los originales desde el backup para estas fallas
SELECT b.id, b.fase_id, b.seccion, b.enunciado AS enunciado_original
FROM _backup_desafios_f4_f5 b
JOIN preguntas p ON p.id = b.id
WHERE p.enunciado LIKE '%ERROR_CAPTURA%'
ORDER BY b.id;

ROLLBACK;
