"""Add SimuladoSession table

Revision ID: bd37b111d579
Revises: b2c3d4e5f6g7
Create Date: 2026-06-14 11:08:07.532479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd37b111d579'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alternativas', 'tipo_error',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CALCULO', 'LECTURA', 'ATENCION', 'OPERACION_INCORRECTA', 'NO_IDENTIFICA_DATOS', 'PROBLEMA_INCOMPLETO', 'TABUADA', 'DIVISION', 'VALOR_POSICIONAL', 'TROCO', 'INFERENCIA', name='tipo_error_alternativas', native_enum=False),
               existing_nullable=True)
    op.create_index('idx_alternativas_pregunta', 'alternativas', ['pregunta_id'], unique=False)
    op.drop_constraint(op.f('alternativas_pregunta_id_fkey'), 'alternativas', type_='foreignkey')
    op.create_foreign_key(None, 'alternativas', 'preguntas', ['pregunta_id'], ['id'])
    op.alter_column('alumnos', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', name='status_alumnos', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.alter_column('configuracion_progreso', 'operacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_config', native_enum=False),
               existing_nullable=False)
    op.create_index('idx_config_fase_seccion_operacion', 'configuracion_progreso', ['fase_id', 'seccion', 'operacion'], unique=False)
    op.alter_column('fases', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', name='status_fases', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_constraint(op.f('intento_preguntas_alumno_id_fkey'), 'intento_preguntas', type_='foreignkey')
    op.drop_constraint(op.f('intento_preguntas_pregunta_id_fkey'), 'intento_preguntas', type_='foreignkey')
    op.create_foreign_key(None, 'intento_preguntas', 'alumnos', ['alumno_id'], ['id'])
    op.create_foreign_key(None, 'intento_preguntas', 'preguntas', ['pregunta_id'], ['id'])
    op.alter_column('intentos', 'operacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_intentos', native_enum=False),
               existing_nullable=False)
    op.alter_column('intentos', 'tipo_error',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CALCULO', 'LECTURA', 'ATENCION', 'OPERACION_INCORRECTA', 'NO_IDENTIFICA_DATOS', 'PROBLEMA_INCOMPLETO', 'TABUADA', 'DIVISION', 'VALOR_POSICIONAL', 'TROCO', 'INFERENCIA', name='tipo_error_intentos', native_enum=False),
               existing_nullable=True)
    op.alter_column('intentos', 'explicacion_mostrada',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_intentos_alumno_bloque', 'intentos', ['alumno_id', 'fase_id', 'seccion', 'operacion'], unique=False)
    op.create_index('idx_intentos_alumno_fecha', 'intentos', ['alumno_id', 'fecha'], unique=False)
    op.create_index('idx_intentos_pregunta', 'intentos', ['pregunta_id'], unique=False)
    op.create_index('idx_intentos_tipo_error', 'intentos', ['tipo_error'], unique=False)
    op.drop_constraint(op.f('intentos_pregunta_id_fkey'), 'intentos', type_='foreignkey')
    op.drop_constraint(op.f('intentos_alumno_id_fkey'), 'intentos', type_='foreignkey')
    op.create_foreign_key(None, 'intentos', 'preguntas', ['pregunta_id'], ['id'])
    op.create_foreign_key(None, 'intentos', 'alumnos', ['alumno_id'], ['id'])
    op.drop_index(op.f('idx_niveles_teoria_pool_modulo'), table_name='niveles_teoria_pool')
    op.drop_index(op.f('idx_niveles_teoria_pool_nivel'), table_name='niveles_teoria_pool')
    op.create_index(op.f('ix_niveles_teoria_pool_id'), 'niveles_teoria_pool', ['id'], unique=False)
    op.create_index(op.f('ix_niveles_teoria_pool_modulo_id'), 'niveles_teoria_pool', ['modulo_id'], unique=False)
    op.create_index(op.f('ix_niveles_teoria_pool_nivel_id'), 'niveles_teoria_pool', ['nivel_id'], unique=False)
    op.alter_column('platform_settings', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('platform_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pool_asignado_alumno', 'operacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_pool', native_enum=False),
               existing_nullable=False)
    op.create_index('idx_pool_alumno_bloque', 'pool_asignado_alumno', ['alumno_id', 'fase_id', 'seccion', 'operacion'], unique=False)
    op.create_index('idx_pool_pendientes', 'pool_asignado_alumno', ['alumno_id', 'fase_id', 'seccion', 'operacion', 'respondida_correctamente'], unique=False)
    op.drop_constraint(op.f('pool_asignado_alumno_alumno_id_fkey'), 'pool_asignado_alumno', type_='foreignkey')
    op.drop_constraint(op.f('pool_asignado_alumno_pregunta_id_fkey'), 'pool_asignado_alumno', type_='foreignkey')
    op.create_foreign_key(None, 'pool_asignado_alumno', 'alumnos', ['alumno_id'], ['id'])
    op.create_foreign_key(None, 'pool_asignado_alumno', 'preguntas', ['pregunta_id'], ['id'])
    op.alter_column('preguntas', 'operacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_preguntas', native_enum=False),
               existing_nullable=False)
    op.alter_column('preguntas', 'tipo_pregunta',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CALCULO_DIRECTO', 'PROBLEMA_CONTEXTO', 'PROBLEMA_MIXTO', 'IDENTIFICAR_OPERACION', 'MULTIPLE_OPCION', 'RESPUESTA_NUMERICA', 'SUBRAYADO_TOKENS', 'CONSTRUCTOR_CHAINED', name='tipo_pregunta_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('preguntas', 'payload_tokenizado',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('preguntas', 'explicacion_paso_a_paso',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('preguntas', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', name='status_preguntas', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index(op.f('idx_preguntas_estructura_padre_id'), table_name='preguntas')
    op.create_index('idx_preguntas_fase_seccion_operacion_estado', 'preguntas', ['fase_id', 'seccion', 'operacion', 'estado'], unique=False)
    op.create_index(op.f('ix_preguntas_estructura_padre_id'), 'preguntas', ['estructura_padre_id'], unique=False)
    op.alter_column('progreso_maestria', 'operacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_progreso', native_enum=False),
               existing_nullable=False)
    op.alter_column('progreso_maestria', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('BLOQUEADO', 'EN_PROGRESO', 'EN_REVISION', 'APROBADO', name='estado_progreso_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'bloqueado'::character varying"))
    op.create_index('idx_progreso_alumno_estado', 'progreso_maestria', ['alumno_id', 'estado'], unique=False)
    op.create_index('idx_progreso_alumno_fase', 'progreso_maestria', ['alumno_id', 'fase_id'], unique=False)
    op.drop_constraint(op.f('progreso_maestria_alumno_id_fkey'), 'progreso_maestria', type_='foreignkey')
    op.create_foreign_key(None, 'progreso_maestria', 'alumnos', ['alumno_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('users', 'unlocked_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'unlocked_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.drop_constraint(None, 'progreso_maestria', type_='foreignkey')
    op.create_foreign_key(op.f('progreso_maestria_alumno_id_fkey'), 'progreso_maestria', 'alumnos', ['alumno_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_progreso_alumno_fase', table_name='progreso_maestria')
    op.drop_index('idx_progreso_alumno_estado', table_name='progreso_maestria')
    op.alter_column('progreso_maestria', 'estado',
               existing_type=sa.Enum('BLOQUEADO', 'EN_PROGRESO', 'EN_REVISION', 'APROBADO', name='estado_progreso_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'bloqueado'::character varying"))
    op.alter_column('progreso_maestria', 'operacion',
               existing_type=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_progreso', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_preguntas_estructura_padre_id'), table_name='preguntas')
    op.drop_index('idx_preguntas_fase_seccion_operacion_estado', table_name='preguntas')
    op.create_index(op.f('idx_preguntas_estructura_padre_id'), 'preguntas', ['estructura_padre_id'], unique=False)
    op.alter_column('preguntas', 'estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', name='status_preguntas', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.alter_column('preguntas', 'explicacion_paso_a_paso',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('preguntas', 'payload_tokenizado',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('preguntas', 'tipo_pregunta',
               existing_type=sa.Enum('CALCULO_DIRECTO', 'PROBLEMA_CONTEXTO', 'PROBLEMA_MIXTO', 'IDENTIFICAR_OPERACION', 'MULTIPLE_OPCION', 'RESPUESTA_NUMERICA', 'SUBRAYADO_TOKENS', 'CONSTRUCTOR_CHAINED', name='tipo_pregunta_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('preguntas', 'operacion',
               existing_type=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_preguntas', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'pool_asignado_alumno', type_='foreignkey')
    op.drop_constraint(None, 'pool_asignado_alumno', type_='foreignkey')
    op.create_foreign_key(op.f('pool_asignado_alumno_pregunta_id_fkey'), 'pool_asignado_alumno', 'preguntas', ['pregunta_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pool_asignado_alumno_alumno_id_fkey'), 'pool_asignado_alumno', 'alumnos', ['alumno_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_pool_pendientes', table_name='pool_asignado_alumno')
    op.drop_index('idx_pool_alumno_bloque', table_name='pool_asignado_alumno')
    op.alter_column('pool_asignado_alumno', 'operacion',
               existing_type=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_pool', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('platform_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_settings', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_niveles_teoria_pool_nivel_id'), table_name='niveles_teoria_pool')
    op.drop_index(op.f('ix_niveles_teoria_pool_modulo_id'), table_name='niveles_teoria_pool')
    op.drop_index(op.f('ix_niveles_teoria_pool_id'), table_name='niveles_teoria_pool')
    op.create_index(op.f('idx_niveles_teoria_pool_nivel'), 'niveles_teoria_pool', ['nivel_id'], unique=False)
    op.create_index(op.f('idx_niveles_teoria_pool_modulo'), 'niveles_teoria_pool', ['modulo_id'], unique=False)
    op.drop_constraint(None, 'intentos', type_='foreignkey')
    op.drop_constraint(None, 'intentos', type_='foreignkey')
    op.create_foreign_key(op.f('intentos_alumno_id_fkey'), 'intentos', 'alumnos', ['alumno_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('intentos_pregunta_id_fkey'), 'intentos', 'preguntas', ['pregunta_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_intentos_tipo_error', table_name='intentos')
    op.drop_index('idx_intentos_pregunta', table_name='intentos')
    op.drop_index('idx_intentos_alumno_fecha', table_name='intentos')
    op.drop_index('idx_intentos_alumno_bloque', table_name='intentos')
    op.alter_column('intentos', 'explicacion_mostrada',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('intentos', 'tipo_error',
               existing_type=sa.Enum('CALCULO', 'LECTURA', 'ATENCION', 'OPERACION_INCORRECTA', 'NO_IDENTIFICA_DATOS', 'PROBLEMA_INCOMPLETO', 'TABUADA', 'DIVISION', 'VALOR_POSICIONAL', 'TROCO', 'INFERENCIA', name='tipo_error_intentos', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('intentos', 'operacion',
               existing_type=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_intentos', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'intento_preguntas', type_='foreignkey')
    op.drop_constraint(None, 'intento_preguntas', type_='foreignkey')
    op.create_foreign_key(op.f('intento_preguntas_pregunta_id_fkey'), 'intento_preguntas', 'preguntas', ['pregunta_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('intento_preguntas_alumno_id_fkey'), 'intento_preguntas', 'alumnos', ['alumno_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fases', 'estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', name='status_fases', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index('idx_config_fase_seccion_operacion', table_name='configuracion_progreso')
    op.alter_column('configuracion_progreso', 'operacion',
               existing_type=sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'MIXTA', name='operacion_config', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('alumnos', 'estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', name='status_alumnos', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_constraint(None, 'alternativas', type_='foreignkey')
    op.create_foreign_key(op.f('alternativas_pregunta_id_fkey'), 'alternativas', 'preguntas', ['pregunta_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_alternativas_pregunta', table_name='alternativas')
    op.alter_column('alternativas', 'tipo_error',
               existing_type=sa.Enum('CALCULO', 'LECTURA', 'ATENCION', 'OPERACION_INCORRECTA', 'NO_IDENTIFICA_DATOS', 'PROBLEMA_INCOMPLETO', 'TABUADA', 'DIVISION', 'VALOR_POSICIONAL', 'TROCO', 'INFERENCIA', name='tipo_error_alternativas', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
